---


- name: install nfs rpm
  yum: name="nfs-utils,rpcbind" state=present

- include_tasks: shell.yml
  vars:
    exec_host: "{{ groups.worker[-1] }}"
  loop: 
    - "mkdir -p {{nfs_data_dirs|join(' ')}}"
    - chmod -R 777 /data 
  tags:
    - nfs_datadir

- name: nfs config
  template: src="{{item.src}}" dest="{{item.dest}}"
  loop:
    - { src: nfs.j2, dest: /etc/sysconfig/nfs }
    - { src: exports.j2, dest: /etc/exports }
  notify:
    - restart nfs
    - restart rpcbind

- meta: flush_handlers

- include_tasks: shell.yml
  vars:
    exec_host: "{{ groups.worker[-1] }}"
  loop: 
    - "showmount -e {{hostvars[groups.worker[-1]].ip}}"
  tags:
    - nfs_check
