
- name: restart rpcbind
  systemd: 
    name: rpcbind
    enabled: yes
    daemon_reload: yes 
    state: restarted

- name: restart nfs
  systemd: 
    name: nfs
    enabled: yes
    daemon_reload: yes 
    state: restarted
