- hosts: all
  run_once: yes
  tasks:
    - name: Make sure cache directory exists
      file:
        path: "{{ vagrant_home }}/cache/{{ ansible_distribution }}/{{ ansible_distribution_version }}/"
        state: directory
      delegate_to: localhost
      when: vagrant_cache

- hosts: all
  become: yes
  vars_files:
    - "global_vars.yml"
  roles:
    - common
  environment:
    https_proxy: 'http://192.168.10.1:7890'
    http_proxy: 'http://192.168.10.1:7890'

#- hosts: master
#  become: yes
#  become_method: sudo
#  vars_files:
#    - "global_vars.yml"
#  roles:
#    - master
#
#- hosts: nodes
#  become: yes
#  become_method: sudo
#  vars_files:
#    - "global_vars.yml"
#  roles:
#    - nodes
#
#- hosts: nodes
#  run_once: yes
#  become: yes
#  vars_files:
#    - "global_vars.yml"
#  tasks:
#    - include_role:
#        name: master
#        tasks_from: yum_cache.yml
#      when: vagrant_cache
#      tags: cache
