---


- name: create app dir
  file: path={{item.name}} mode={{item.mode}} state=directory
  loop:
    - {name: /etc/etcd, mode: 755}
    - {name: /var/lib/etcd, mode: 700}

- name: copy config
  copy: src={{item}} dest=/etc/etcd/ remote_src=yes force=yes
  loop:
    - ca.pem
    - kubernetes-key.pem
    - kubernetes.pem

- name: set etcd command client
  template: src="etcd_ctl.sh.j2" dest="/usr/local/bin/etcd_ctl" mode=0755
  tags: 
    - etcd_ctl

- name: set etcd service
  template: src="etcd.service.j2" dest="/etc/systemd/system/etcd.service" force=yes
  notify:
    - restart etcd

- meta: flush_handlers

- block:
  - name: check status
    register: result
    shell: "etcd_ctl endpoint status"
  - debug: var=result.stdout_lines
  run_once: true

