# -*- mode: ruby -*-
# vi: set ft=ruby :

NODES = 3
DISKS = 2
DISKS_SIZE=10
CACHE = true
USE_PROXY = true
DISK_DIR = "./volumes"
LIBVIRT_DISK_CACHE = "default"
NETWORK_IP_PREFIX = "192.168.0.6"
HOST_NAME_TPL = "node%01d.hw.cn"
SETTINGS = {}
IP_ADDRS = {}
host_vars = {}
SETTINGS['ssh_path'] = "~/.ssh"
SETTINGS['authorize'] = "#{SETTINGS['ssh_path']}/id_rsa.pub"
SETTINGS['key'] = "#{SETTINGS['ssh_path']}/id_rsa"
NTP_SERVER = "192.168.0.14"
REGISTRY_SERVER = "192.168.0.14"
PORXY_ADDR="http://192.168.0.112:7890"

NO_PROXY=(1..NODES).map {|j| "#{NETWORK_IP_PREFIX}#{j}"}
NO_PROXY.push("127.0.0.1","localhost","myharbor.com")

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.ssh.username = "vagrant"
    config.vm.box = "centos/7"
    config.vm.box_url = "https://app.vagrantup.com/centos/7"
    config.vm.box_version = "2004.01"
    config.vm.box_check_update = false
    config.vbguest.auto_update = false
    #config.vm.synced_folder '/Users/tonywu/Downloads', '/home/vagrant/sync', type: "nfs", linux__nfs_options: ['rw','no_subtree_check','all_squash','async']

    if SETTINGS.include? 'authorize'
        if File.exist? File.expand_path(SETTINGS['authorize'])
          config.vm.provision 'shell' do |s|
            s.inline = "echo $1 | grep -xq \"$1\" /home/vagrant/.ssh/authorized_keys || echo \"\n$1\" | tee -a /home/vagrant/.ssh/authorized_keys;"
            s.args = [File.read(File.expand_path(SETTINGS['authorize']))]
          end
        end
    end
    if SETTINGS.include? 'key'
        if File.exist? File.expand_path(SETTINGS['key'])
            config.vm.provision 'shell' do |s|
              s.privileged = false
              s.inline = "echo \"$1\" > /home/vagrant/.ssh/$2 && chmod 600 /home/vagrant/.ssh/$2"
              s.args = [File.read(File.expand_path(SETTINGS['key'])), SETTINGS['key'].split('/').last]
            end
        end
    end
 
    config.vm.synced_folder ".", "/vagrant", disabled: true
    #config.vm.synced_folder "files/k8s_demo", "/home/vagrant/k8s_demo",create: true, type: "rsync", rsync__args: ['--verbose', '--archive', '--delete', '-z']
  
    # disable usb
    config.vm.provider "virtualbox" do |vb|
      # VM Customizations go here
      vb.customize ["modifyvm", :id, "--usb", "off"]
      vb.customize ["modifyvm", :id, "--usbehci", "off"]
    end


    $script = <<-'SCRIPT'
    scp -r  /home/vagrant/.ssh /root/
    sed -i '/PasswordAuthentication/s/no/yes/g' /etc/ssh/sshd_config; systemctl restart sshd
    SCRIPT
    config.vm.provision "config",type: "shell", inline: $script, privileged: true
    

    (1..NODES).each do |i|
        IP_ADDRS["hw-node#{i}"] = "#{NETWORK_IP_PREFIX}#{i}"
        config.vm.define vm_name = HOST_NAME_TPL % [i] do |node|
            node.vm.hostname = vm_name
            node.vm.network "public_network", ip: "#{NETWORK_IP_PREFIX}#{i}",bridge: "en0: 以太网"
            node.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
            node.vm.network :forwarded_port, guest: 22, host: "225#{i}", auto_correct: true
            # 全局代理影响太大,故取消；改在containerd服务配置使用代理
            # if Vagrant.has_plugin?("vagrant-proxyconf")
            #     node.proxy.http     = ENV['HTTP_PROXY'] || ENV['http_proxy'] || "http://192.168.0.112:7890"
            #     node.proxy.https    = ENV['HTTPS_PROXY'] || ENV['https_proxy'] ||  "http://192.168.0.112:7890"
            #     node.proxy.no_proxy = ENV['NO_PROXY'] || ENV['no_proxy'] || "#{NO_PROXY.join(',')}"
            # end
            # Settings for Virtualbox
            # 每个node执行一次
            node.vm.provider :virtualbox do |vb|
                unless File.exist?("#{DISK_DIR}/hw-disk-#{i}-1.vdi")
                    #vb.customize ["storagectl", :id,"--name", "VboxSata", "--remove"]
                    vb.customize ["storagectl", :id,"--name", "VboxSata", "--add", "sata"]
                end
            end
            # 每个disk执行一次
            # To make the glusterfs cluster, each with DISKS number of drives
            (1..DISKS).each do |d|
                node.vm.provider :virtualbox do |vb|
                    unless File.exist?("#{DISK_DIR}/hw-disk-#{i}-#{d}.vdi")
                       vb.customize [ "createmedium", "--filename", "#{DISK_DIR}/hw-disk-#{i}-#{d}.vdi", "--size", 1024*DISKS_SIZE]
                    end
                    vb.customize [ "storageattach", :id, "--storagectl", "VboxSata", "--port", 3+d, "--device", 0, "--type", "hdd", "--medium", "#{DISK_DIR}/hw-disk-#{i}-#{d}.vdi" ]  
                    vb.memory = 6144
                    vb.cpus = 2
                end
            end
            host_vars[vm_name] = {
                "ip": "#{NETWORK_IP_PREFIX}#{i}"
            } 
            if i == 1 
               node.vm.provision :ansible do |ansible|
                    #ansible.verbose = true
                    ansible.host_key_checking = false
                    #sudo问题很多，不建议使用
                    #ansible.become = true
                    ansible.limit = "all"
                    ansible.host_vars = host_vars
                    ansible.raw_arguments  = [
                     "-t preinstall,certs,etcd"
                    ]       
                    ansible.playbook = "k8s_playbook_new/cluster.yml"
                    ansible.groups = {
                        "master" => (1..NODES-1).map {|i| HOST_NAME_TPL % [i]},
                        "worker" => (1..NODES).map {|i| HOST_NAME_TPL % [i]},
                        "etcd" => (1..NODES).map {|i| HOST_NAME_TPL % [i]},
                        "k8s_cluster:children" => ["master", "worker"],
                    }
                    ansible.extra_vars = {
                        "http_proxy"  => PORXY_ADDR,
                        "no_proxy" => NO_PROXY,
                        "use_proxy" => USE_PROXY,
                        "vagrant_cache" => ENV['VAGRANT_CACHE'] ? ENV['VAGRANT_CACHE'] : CACHE,
                        "ntp_server"  => NTP_SERVER,
                        "myharbor_server" => REGISTRY_SERVER,
                         #ansible执行需要root
                        "ansible_user" => "root",
                        "ip_addrs" => IP_ADDRS
                   }
               end
            end
        end
    end
end
 