- name: Hosts | create list from inventory
  set_fact:
    etc_hosts_inventory_block: |-
      {% for item in (groups['k8s_cluster'] + groups['etcd']|default([]))|unique -%}
      {{ hostvars[item]['ansible_host'] }}
      {%- if ('ansible_hostname' in hostvars[item] and item != hostvars[item]['ansible_hostname']) %}  {{ hostvars[item]['ansible_hostname'] }}{% endif %} {{ item }}
      {% endfor %}
      {% if myharbor_server|default('') != '' %}
      {{ myharbor_server }} myharbor.com
      {% endif %}
  delegate_to: localhost
  connection: local
  delegate_facts: yes
  run_once: yes

- debug: var=hostvars.localhost.etc_hosts_inventory_block
  run_once: yes


- name: Hosts | populate inventory into hosts file
  blockinfile:
    path: /etc/hosts
    block: "{{ hostvars.localhost.etc_hosts_inventory_block }}"
    state: present
    create: yes
    backup: yes
    unsafe_writes: yes
    marker: "# Ansible inventory hosts {mark}"
    mode: 0644
  when: populate_inventory_to_hosts_file

