{{- if and .Values.blackboxExporter.enabled .Values.blackboxExporter.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kube-prometheus.blackboxExporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "kube-prometheus.blackboxExporter.labels" . | nindent 4 }}
  {{- if index .Values.blackboxExporter.serviceAccount.annotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.blackboxExporter.serviceAccount.annotations "context" $) | nindent 4 }}
  {{- end }}
{{- include "kube-prometheus.imagePullSecrets" . }}
{{- end }}
