- block:
  - name: addon images copy
    synchronize: src=images dest=/tmp
  - name: docker_load
    import_role:
      name: worker_svc
      tasks_from: docker_load.yml
  tags:
    - dockerload
  when: use_cache

