
- block:
  - name: addon images copy
    synchronize: src="{{item}}" dest=/tmp/
    loop:
      - images
      - charts
  - name: docker_load
    import_role:
      name: worker_svc
      tasks_from: docker_load.yml
  tags:
    - dockerload
  when: use_cache


- import_tasks: csi-driver-nfs.yml
  tags:
    - nfs-cis-chart 

- block:
  - shell: "kubectl get ns monitor || kubectl create ns monitor"
  - import_tasks: grafana.yml
    tags:
      - grafana
  - import_tasks: prometheus.yml
    tags:
      - prometheus
  tags:
    - monitor
