---

- include_role:
    name: addon
    tasks_from: apply.yml
  loop:
    - { name: nginx-ds, yaml: "{{role_path}}/templates/nginx-ds.yaml" }
    - { name: pod-nginx, yaml: "{{role_path}}/templates/pod-nginx.yaml" }
  tags:
    - apply

- include_role:
    name: addon
    tasks_from: shell.yml
  loop:
    - kubectl create ns dev & >/dev/null
    - kubectl create ns test & >/dev/null
    - kubectl exec nginx -- cat /etc/resolv.conf 
    - kubectl exec nginx -- curl -I -s $(kubectl get pods -l app=nginx-ds -o jsonpath="{.items[0].status.podIP}")
    - kubectl exec nginx -- curl -I -s nginx-ds 
    - kubectl exec -it $(kubectl get pods -l app=nginx-ds -o jsonpath="{.items[0].metadata.name}") -- nginx -v
    - kubectl logs nginx
  tags:
    - pod_test

    
- import_tasks: glusterfs_test.yml 
  tags:
    - glusterfs_test

- include_tasks: nfs_test.yml 
  tags:
    - nfs_test
- import_tasks: nfs_client_provisioner_test.yml 
  run_once: true
  tags:
    - nfs_client_provisioner_test
- include_tasks: nfs_csi_driver_test.yml
  when: install_charts
  tags:
    - nfs_csi_test
