kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glusterfs-pvc
spec:
  storageClassName: {{glusterfs_sc}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

