---
cluster_cidr: "10.200.0" 
service_cluster_ip_range: "10.233.0"
cluster_dns: "169.254.25.10"
#calico_bind_interface: "eth1"
COREDNS_CLUSTER_IP: "10.233.0.10"

container_proxy: true
http_proxy: "http://192.168.0.112:7890"
no_proxy: "192.168.0.51,192.168.0.52,192.168.0.53,127.0.0.1,localhost,myharbor.com"
ntp_server: '192.168.0.14'
use_cache: true
install_charts: true
populate_inventory_to_hosts_file: true
customed_containerd_toml: true

#主机网络信息
host_ip_range: "{{hostvars[groups.worker[-1]].ip.split('.')[0:3]|join('.')}}"
host_prefix: '24'

#存储类名称
nfs_sc: ""
glusterfs_sc: ""