---

- name: install glusterfs client rpm
  yum: name="{{item}}" state=present
  loop:
    - glusterfs
    - glusterfs-fuse


- block:
  - name: modprobe for glusterfs
    register: modprobe
    script: 'modprobe.sh'
  - debug: var=modprobe.stdout_lines
  tags:
    - modprobe
